version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - playground

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    restart: unless-stopped

volumes:
  postgres_db:

networks:
  playground:
    driver: bridge